name=SenseAir_S88_Async
version=1.2.0
author=Oleksandr Specled
maintainer=Oleksandr Specled <specled@inbox.eu>
sentence=Asynchronous, non-blocking Modbus library for SenseAir S8 CO2 sensors.
paragraph=Features a robust State Machine, CRC16 validation, ring buffer for command queuing, and self-healing mechanisms for lost connections. Designed for high-reliability systems and ESP32/ESP8266/Arduino architectures.
category=Sensors
url=https://github.com/specledcomua-creator/SenseAir_S88
architectures=*
includes=SenseAir_S88.h
license=MIT